### ISSUE TITLE
Link to a section

### ISSUE THREAD

**Issue by TanishqSinghAnand** [Nazeh-Taha/react-responsive-animate-navbar#30]
While directed to a section the link changes to 'localhost:3000/#about' the link changes but it does not actually directs to that section of the page

**Comment by lorstenoplo** [comment]
Can you try providing an example like codesandbox with the issue reproduced

**Comment by TanishqSinghAnand** [comment]
> Can you try providing an example like codesandbox with the issue reproduced

https://codesandbox.io/s/elastic-darkness-j9won?file=/src/App.js

**Comment by lorstenoplo** [comment]
Check this so question : https://stackoverflow.com/questions/43441856/how-to-scroll-to-an-element

The accepted answer says string refs are deprecated in react so it's react related not particular to this library use `scrollIntoView` but using `useRef` hook that's the best to date

**Comment by TanishqSinghAnand** [comment]
Okay, thanks a lot for your support!
